config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :orders do
      resources :return_authorizations do
        resources :return_labels
      end
    end

    resources :scan_forms, only: [:index, :new, :create]

    resources :customer_shipments_tracking, only: [:index]

    resources :easypost_settings, only: [:edit, :update]
  end

  namespace :api do
    namespace :v1 do
      resources :customer_shipments do
        
      end

      resources :shipments do
        member do
          put :buy_postage
        end
      end

      post "/scan_form" => "shipments#scan_form"

    end
  end
end

app/controllers/spree/admin/easypost_settings_controller.rb
module Spree
  module Admin
    class EasypostSettingsController < Spree::Admin::BaseController
      before_action :load_stock_locations, only: [:edit, :update]

      def edit
      end

      def update
        update_easypost_settings

        redirect_to :back
      end

      private

      def load_stock_locations
        @stock_locations = Spree::StockLocation.all
      end

      def update_easypost_settings
        easypost_settings_params.each do |key, value|
          Spree::Config[key] = value
        end
      end

      def easypost_settings_params
        params.require(:settings).permit(
            :buy_postage_when_shipped,
            :validate_address_with_easypost,
            :use_easypost_on_frontend,
            :customs_signer,
            :customs_contents_type,
            :customs_eel_pfc,
            :carrier_accounts_shipping,
            :carrier_accounts_returns,
            :endorsement_type,
            :returns_stock_location_id,
        )
      end
    end
  end
end

app/views/spree/admin/easypost_settings/edit.html.erb
<h1><%= t('easypost_settings') %></h1>

<%= form_tag admin_easypost_setting_path, method: :put, id: :easypost_settings_form do %>
  <div class="yui-g">
    <div class="yui-u first">
      <fieldset>
        <p>
          <label><%= t('buy_postage_when_shipped') %></label><br />
          <%= hidden_field_tag 'settings[buy_postage_when_shipped]', false %>
          <%= check_box_tag 'settings[buy_postage_when_shipped]', true, Spree::Config.buy_postage_when_shipped, class: 'easypost' %>
        </p>

        <p>
          <label><%= t('use_easypost_on_frontend') %></label><br />
          <%= hidden_field_tag 'settings[use_easypost_on_frontend]', false %>
          <%= check_box_tag 'settings[use_easypost_on_frontend]', true, Spree::Config.use_easypost_on_frontend, class: 'easypost' %>
        </p>

        <p>
          <label><%= t('validate_address_with_easypost') %></label><br />
          <%= hidden_field_tag 'settings[validate_address_with_easypost]', false %>
          <%= check_box_tag 'settings[validate_address_with_easypost]', true, Spree::Config.validate_address_with_easypost, class: 'easypost' %>
        </p>

        <p>
          <label><%= t('customs_signer') %></label><br />
          <%=  text_field_tag 'settings[customs_signer]', Spree::Config.customs_signer %>
        </p>

        <p>
          <label><%= t('customs_contents_type') %></label><br />
          <%=  text_field_tag 'settings[customs_contents_type]', Spree::Config.customs_contents_type %>
        </p>

        <p>
          <label><%= t('customs_eel_pfc') %></label><br />
          <%=  text_field_tag 'settings[customs_eel_pfc]', Spree::Config.customs_eel_pfc %>
        </p>

        <p>
          <label><%= t('carrier_accounts_shipping') %></label><br />
          <%=  text_field_tag 'settings[carrier_accounts_shipping]', Spree::Config.carrier_accounts_shipping %>
        </p>

        <p>
          <label><%= t('carrier_accounts_returns') %></label><br />
          <%=  text_field_tag 'settings[carrier_accounts_returns]', Spree::Config.carrier_accounts_returns %>
        </p>

        <p>
          <label><%= t('endorsement_type') %></label><br />
          <%=  text_field_tag 'settings[endorsement_type]', Spree::Config.endorsement_type %>
        </p>

        <p>
          <label><%= t('returns_center_stock_location') %></label><br />
          <%=  select_tag 'settings[returns_stock_location_id]', options_from_collection_for_select(@stock_locations, "id", "admin_name", Spree::Config.returns_stock_location_id) %>
        </p>
      </fieldset>
    </div>
  </div>

  <p class="form-buttons"><%= button t('save_preferences') %></p>
<% end %>