config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :orders do
      resources :return_authorizations do
        resources :return_labels
      end
    end

    resources :scan_forms, only: [:index, :new, :create]

    resources :customer_shipments_tracking, only: [:index]

    resources :easypost_settings, only: [:edit, :update]
  end

  namespace :api do
    namespace :v1 do
      resources :customer_shipments do
        
      end

      resources :shipments do
        member do
          put :buy_postage
        end
      end

      post "/scan_form" => "shipments#scan_form"

    end
  end
end

app/controllers/spree/admin/scan_forms_controller.rb
module Spree
    module Admin
      class ScanFormsController < ResourceController

        before_action :load_data, only: [:new, :create]

        def index
          params[:q] ||= {}
  
          @scan_forms = ScanForm.all
        
          @search = @scan_forms.ransack(params[:q])
          per_page = params[:per_page] || Spree::Config[:admin_products_per_page]
          @scan_forms = @search.result.order(created_at: :desc).page(params[:page]).per(per_page)

          respond_with(@scan_forms)
        end

        private

        def load_data
          @stock_locations = Spree::StockLocation.order(:name)
        end

        def model_class
          Spree::ScanForm
        end

      end
    end
  end

app/views/spree/admin/scan_forms/_form.html.erb
<div data-hook="admin_stock_locations_form_fields">

  <div class="form-group" data-hook="stock_location_country">
    <%= f.label :stock_location_id, Spree.t(:stock_location) %>
    <span id="stock_location"><%= f.collection_select :stock_location_id, @stock_locations, :id, :name, {}, { class: 'select2' } %></span>
  </div>
 
</div>

app/views/spree/admin/scan_forms/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:scan_forms) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_scan_form), new_admin_scan_form_url, :class => "btn-success", :icon => 'add', :id => 'admin_new_scan_form' %>
<% end if can? :create, Spree::ScanForm %>

<% content_for :table_filter do %>
  <div data-hook="admin_scan_forms_index_filters">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <%= f.label :number_cont, Spree.t(:number) %>
            <%= f.text_field :number_cont, class: "form-control js-quick-search-target" %>
          </div>
        </div>
      </div>
      <div data-hook="admin_scan_forms_index_filters_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @scan_forms %>

<% if @scan_forms.any? %>
  <table class="table">
    <thead>
      <tr data-hook="rate_header">
        <th><%= Spree.t(:created_at) %></th>
        <th><%= Spree.t(:number) %></th>
        <th><%= Spree.t(:stock_location) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @scan_forms.each do |scan_form| %>
        <tr id="<%= spree_dom_id scan_form %>" data-hook="scan_form_row">
          <td><%= scan_form.created_at.to_date %></td>
          <td><%= scan_form.number %></td>
          <td><%= scan_form.stock_location.admin_name %></td>
          <td class="actions actions-1 text-right">
            <%= link_to_with_icon 'file', Spree.t('scan_form'), scan_form.scan_form, class: 'scanform-item btn btn-primary btn-sm', title: Spree.t('scan_form'), no_text: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree::ScanForm.model_name.human(count: :many)) %>.
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @scan_forms, simple: true %>

app/views/spree/admin/scan_forms/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:scan_forms), spree.admin_scan_forms_url %> /
  <%= Spree.t(:new_scan_form) %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @scan_form } %>

<%= form_for [:admin, @scan_form] do |f| %>
  <fieldset>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>