config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
    resources :orders do
      resources :return_authorizations do
        resources :return_labels
      end
    end

    resources :scan_forms, only: [:index, :new, :create]

    resources :customer_shipments_tracking, only: [:index]

    resources :easypost_settings, only: [:edit, :update]
  end

  namespace :api do
    namespace :v1 do
      resources :customer_shipments do
        
      end

      resources :shipments do
        member do
          put :buy_postage
        end
      end

      post "/scan_form" => "shipments#scan_form"

    end
  end
end

app/controllers/spree/admin/customer_shipments_tracking_controller.rb
module Spree 
    module Admin
      class CustomerShipmentsTrackingController < ResourceController

        def index
          @tracking_number = params[:tracking]
          return if @tracking_number.nil?
          parse_tracking_nubmer
          @customer_shipment = Spree::CustomerShipment.find_by(tracking: @tracking_number)
          if @customer_shipment
            @order = @customer_shipment.return_authorization.order
            redirect_to new_admin_order_customer_return_path(@order)
          else
            flash[:notice] = "Could not find customer shipment."
          end
        end

        def parse_tracking_nubmer
          # USPS barcodes start with 420 and 5 digit zipcode
          # Need to remove the first 8 chars for this to work
          if @tracking_number.start_with?('420')
            @tracking_number = @tracking_number[8..-1]
          end
        end

        private

        def model_class
          Spree::CustomerShipment
        end
 
      end
    end
end

app/views/spree/admin/customer_shipments_tracking/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:customer_shipments) %>
<% end %>

<div class="panel-body">
    <%= form_tag admin_customer_shipments_tracking_index_path, method: :get do %>
    <div class="form-group" id="customer_shipments_tracking_field">
        <%= label_tag :tracking, Spree.t(:tracking) %>
        <%= text_field_tag :tracking, '', :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-actions">
      <%= button Spree.t(:search), 'search', 'search', class: "btn-success" %>
    </div>
    <% end %>
</div>